### PR TITLE
Add common to include path for stdbool.h

### PR DESCRIPTION
**Pull request by gbarta**
Thanks for this native build of sassc!  I found that building the original with Mingw gave me a result prone to segfaults but this one works great.

I found I needed to add the common folder to the include path for it to build. I guess you may have that include set up in another property page not part of the project?

Anyway, Thanks!

### CODE REVIEW

**Comment by gbarta** [comment]
Actually, I can see now that this was only an issue for the Debug build.  For the release build the common folder had already been added to Additional Includes instead of VC++ includes.

**Comment by gbarta** [comment]
Updated to leave Release settings unchanged and only update Debug settings.

**Comment by Articus** [comment]
Thanks for tip :+1:. It seems I forgot to select "All configurations" during adding include directory and Debug configuration was left behind. 
Also thanks to you I noticed that path to libsass was declared relative without path macros. I made a single commit ee5b6f183b2bf71c15fb4d3e3310b655d544a1fa to fix both issues, but have not merged your pull request because of that. Sorry for this.

**Comment by gbarta** [comment]
No worries!

**Pull request closed without merging**
